version: "2.1"
volumes:
  influxdb_data:
  pg_data:
  pg_data_imhash:

services:
  influxdb:
    image: influxdb:alpine
    volumes:
      - influxdb_data:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    ports:
      - 127.0.0.1:3006:3000
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=changeme"
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=feed_archiver"
      - "POSTGRES_PASSWORD=changeme"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U feed_archiver"]
      interval: 5s
      timeout: 5s
      retries: 5
  db_imhashdb:
    image: simon987/pg_hamming
    volumes:
      - pg_data_imhash:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=imhashdb"
      - "POSTGRES_PASSWORD=changeme"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U imhashdb"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis
  archiver:
    image: simon987/feed_archiver
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - "FA_DB_HOST=db"
      - "FA_DB_USER=feed_archiver"
      - "FA_DB_PASSWORD=changeme"
      - "FA_REDIS_ADDR=redis:6379"
      - "FA_PATTERN=arc.*"
  imhashdb:
    image: simon987/imhashdb
    restart: always
    entrypoint: "/build/imhashdb/cli/cli hasher"
    volumes:
      - ${SAVE_FOLDER}:/data/
    environment:
      - "IMHASHDB_STORE=/data"
      - "IMHASHDB_REDIS_ADDR=redis:6379"
      - "IMHASHDB_PG_USER=imhashdb"
      - "IMHASHDB_PG_PASSWORD=changeme"
      - "IMHASHDB_PG_DATABASE=imhashdb"
      - "IMHASHDB_PG_HOST=db_imhashdb"
      - "IMHASHDB_HASH_CONCURRENCY=16"
  # Image boards
  4chan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=4chan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  0chan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=0chan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  22chan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=22chan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  2chan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=2chan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"


  2chhk:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=2chhk"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  38chan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=38chan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  410chan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=410chan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  4kev:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=4kev"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  7chan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=7chan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  8kun:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=8kun"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  alokal:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=alokal"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  aurorachan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=aurorachan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  awsumchan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=awsumchan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  chanon:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=chanon"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  chanorg:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=chanorg"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  desuchan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=desuchan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  doushio:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=doushio"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  endchan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=endchan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  fchan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=fchan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  gnfos:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=gnfos"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  hispachan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=hispachan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  horochan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=horochan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  iichan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=iichan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  lainchan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=lainchan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  lolnada:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=lolnada"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  nowere:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=nowere"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  plus4chan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=plus4chan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  sushigirl:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=sushigirl"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  synch:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=synch"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  tahta:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=tahta"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  tgchan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=tgchan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  uboachan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=uboachan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  waifuist:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=waifuist"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"

  wizchan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=wizchan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"
  9chan:
    image: simon987/chan_feed
    restart: always
    user: ${CURRENT_UID}
    environment:
      - "CF_CHAN=9chan"
      - "CF_REDIS_HOST=redis"
      - "CF_INFLUXDB=influxdb"
