version: "3"

services:
  4chan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=4chan"
      - "REDIS_HOST=redis"

  0chan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=0chan"
      - "REDIS_HOST=redis"

  22chan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=22chan"
      - "REDIS_HOST=redis"

  2chan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=2chan"
      - "REDIS_HOST=redis"


  2chhk:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=2chhk"
      - "REDIS_HOST=redis"

  38chan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=38chan"
      - "REDIS_HOST=redis"

  410chan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=410chan"
      - "REDIS_HOST=redis"

  4kev:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=4kev"
      - "REDIS_HOST=redis"

  7chan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=7chan"
      - "REDIS_HOST=redis"

  8kun:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=8kun"
      - "REDIS_HOST=redis"

  alokal:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=alokal"
      - "REDIS_HOST=redis"

  aurorachan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=aurorachan"
      - "REDIS_HOST=redis"

  awsumchan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=awsumchan"
      - "REDIS_HOST=redis"

  chanon:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=chanon"
      - "REDIS_HOST=redis"

  chanorg:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=chanorg"
      - "REDIS_HOST=redis"

  desuchan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=desuchan"
      - "REDIS_HOST=redis"

  doushio:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=doushio"
      - "REDIS_HOST=redis"

  endchan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=endchan"
      - "REDIS_HOST=redis"

  fchan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=fchan"
      - "REDIS_HOST=redis"

  gnfos:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=gnfos"
      - "REDIS_HOST=redis"

  hispachan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=hispachan"
      - "REDIS_HOST=redis"

  horochan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=horochan"
      - "REDIS_HOST=redis"

  iichan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=iichan"
      - "REDIS_HOST=redis"

  lainchan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=lainchan"
      - "REDIS_HOST=redis"

  lolnada:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=lolnada"
      - "REDIS_HOST=redis"

  nowere:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=nowere"
      - "REDIS_HOST=redis"

  plus4chan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=plus4chan"
      - "REDIS_HOST=redis"

  sushigirl:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=sushigirl"
      - "REDIS_HOST=redis"

  synch:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=synch"
      - "REDIS_HOST=redis"

  tahta:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=tahta"
      - "REDIS_HOST=redis"

  tgchan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=tgchan"
      - "REDIS_HOST=redis"

  uboachan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=uboachan"
      - "REDIS_HOST=redis"

  waifuist:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=waifuist"
      - "REDIS_HOST=redis"

  wizchan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=wizchan"
      - "REDIS_HOST=redis"
  9chan:
    image: simon987/chan_feed
    restart: always
    environment:
      - "CF_CHAN=9chan"
      - "REDIS_HOST=redis"
